import type React from 'react';
import { colors } from '../../theme/tokens';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    backgroundColor: '#000',
    position: 'relative',
  },
  videoWrapper: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
    minHeight: 0,
  },
  video: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
    pointerEvents: 'none',
  },
  // Aspect ratio overlay (preview mode)
  aspectOverlay: {
    position: 'absolute',
    top: '10px',
    right: '10px',
    display: 'flex',
    gap: '4px',
    zIndex: 10,
  },
  aspectBtn: {
    padding: '4px 8px',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    color: '#999',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 600,
    cursor: 'pointer',
    backdropFilter: 'blur(8px)',
    WebkitBackdropFilter: 'blur(8px)',
  },
  aspectBtnActive: {
    backgroundColor: `rgba(255, 107, 53, 0.85)`,
    color: '#fff',
    borderColor: colors.accent,
  },
  // Crosshair overlay
  crosshairOverlay: {
    position: 'absolute',
    inset: 0,
    pointerEvents: 'none',
  },
  // Controls
  controls: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '6px 12px',
    backgroundColor: colors.bg,
    borderTop: '1px solid #333',
  },
  playBtn: {
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.bgSurface,
    color: '#fff',
    border: `1px solid ${colors.borderLight}`,
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '14px',
    flexShrink: 0,
  },
  time: {
    fontSize: '12px',
    color: '#999',
    fontVariantNumeric: 'tabular-nums',
    minWidth: '46px',
    flexShrink: 0,
  },
  seekBarTrack: {
    flex: 1,
    height: '20px',
    position: 'relative',
    cursor: 'pointer',
    backgroundColor: '#333',
    borderRadius: '3px',
    userSelect: 'none',
  },
  trimRegion: {
    position: 'absolute',
    top: 0,
    height: '100%',
    backgroundColor: 'rgba(255, 107, 53, 0.25)',
    borderRadius: '3px',
  },
  trimExcluded: {
    position: 'absolute',
    top: 0,
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  trimHandle: {
    position: 'absolute',
    top: '50%',
    width: '18px',
    height: '36px',
    marginLeft: '-9px',
    transform: 'translateY(-50%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'ew-resize',
    zIndex: 2,
  },
  trimHandleBar: {
    width: '8px',
    height: '32px',
    backgroundColor: colors.accent,
    borderRadius: '4px',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    gap: '3px',
    boxShadow: '0 1px 4px rgba(0, 0, 0, 0.4)',
  },
  trimHandleGrip: {
    width: '4px',
    height: '1px',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    borderRadius: '1px',
  },
  playhead: {
    position: 'absolute',
    top: '-6px',
    width: '8px',
    height: '26px',
    marginLeft: '-4px',
    zIndex: 1,
    pointerEvents: 'none',
  },
  playheadBar: {
    position: 'absolute',
    left: '50%',
    marginLeft: '-1px',
    top: '8px',
    height: 'calc(100% - 8px)',
    width: '2px',
    backgroundColor: colors.accent2,
    boxShadow: '0 1px 4px rgba(0, 0, 0, 0.4)',
  },
  playheadHoop: {
    position: 'absolute',
    left: '50%',
    width: '8px',
    height: '8px',
    borderRadius: '50%',
    border: `2px solid ${colors.accent2}`,
    backgroundColor: 'transparent',
    transform: 'translateX(-50%)',
    boxSizing: 'border-box',
    boxShadow: '0 1px 4px rgba(0, 0, 0, 0.4)',
  },
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    backgroundColor: '#0a0a0a',
  },
  emptyIcon: {
    fontSize: '48px',
    color: '#333',
    marginBottom: '8px',
  },
  emptyText: {
    color: '#555',
    fontSize: '14px',
  },
  spinner: {
    width: '36px',
    height: '36px',
    border: `3px solid rgba(255, 107, 53, 0.2)`,
    borderTopColor: colors.accent,
    borderRadius: '50%',
    animation: 'spin 0.8s ease-in-out infinite',
  },
};
