export const styles: Record<string, React.CSSProperties> = {
  group: {
    display: 'flex',
    alignItems: 'center',
    gap: '7px',
    height: '24px',
  },
  groupLabel: {
    display: 'flex',
    alignItems: 'center',
    color: '#c8c8c8',
  },
  separator: {
    width: '1px',
    height: '16px',
    backgroundColor: '#2a2a2a',
    flexShrink: 0,
    margin: '0 4px',
  },

  // Preview pill (matches GPX chip style from ProjectView)
  previewPillOff: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '3px 10px',
    border: '1px dashed #555',
    borderRadius: '20px',
    cursor: 'pointer',
    fontSize: '11px',
    color: '#777',
    userSelect: 'none' as const,
    transition: 'all 0.15s ease',
  },
  previewPillOn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    padding: '3px 10px',
    border: '1px solid #4a7c59',
    borderRadius: '20px',
    backgroundColor: 'rgba(74, 124, 89, 0.15)',
    cursor: 'pointer',
    fontSize: '11px',
    color: '#8bc49a',
    userSelect: 'none' as const,
    transition: 'all 0.15s ease',
  },
  previewDotOff: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    border: '1px solid #555',
    flexShrink: 0,
  },
  previewDotOn: {
    width: '7px',
    height: '7px',
    borderRadius: '50%',
    backgroundColor: '#6abf7b',
    flexShrink: 0,
  },

  // WS9 — source-format badges. The three colours correspond to
  // `SourceFormatBadge` in lib/sourceFormat.ts:
  //   detected → calm green
  //   suggested → amber (action prompt)
  //   overridden → blue (user intent)
  badgeDetected: {
    display: 'inline-block',
    padding: '2px 6px',
    fontSize: '9px',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    borderRadius: '3px',
    color: '#7fc89a',
    backgroundColor: 'rgba(74, 124, 89, 0.18)',
    border: '1px solid rgba(74, 124, 89, 0.45)',
    whiteSpace: 'nowrap' as const,
    userSelect: 'none' as const,
  },
  badgeSuggested: {
    display: 'inline-block',
    padding: '2px 6px',
    fontSize: '9px',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    borderRadius: '3px',
    color: '#e8b86a',
    backgroundColor: 'rgba(180, 130, 50, 0.18)',
    border: '1px solid rgba(180, 130, 50, 0.55)',
    whiteSpace: 'nowrap' as const,
    cursor: 'help' as const,
    userSelect: 'none' as const,
  },
  badgeOverridden: {
    display: 'inline-block',
    padding: '2px 6px',
    fontSize: '9px',
    fontWeight: 600,
    letterSpacing: '0.06em',
    textTransform: 'uppercase' as const,
    borderRadius: '3px',
    color: '#7fb3e8',
    backgroundColor: 'rgba(70, 120, 180, 0.18)',
    border: '1px solid rgba(70, 120, 180, 0.45)',
    whiteSpace: 'nowrap' as const,
    userSelect: 'none' as const,
  },
};
