import type React from 'react';
import { colors } from '../../theme/tokens';

export const popoverStyles: Record<string, React.CSSProperties> = {
  container: {
    position: 'fixed',
    backgroundColor: '#252525',
    border: `1px solid ${colors.border}`,
    borderRadius: '8px',
    padding: '12px 14px',
    minWidth: '220px',
    zIndex: 200,
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.5)',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  title: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#fff',
    marginBottom: '8px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rows: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    fontSize: '11px',
  },
  label: {
    color: '#777',
  },
  value: {
    color: '#bbb',
    fontVariantNumeric: 'tabular-nums',
  },
};

export const styles: Record<string, React.CSSProperties> = {
  container: {
    width: '100%',
    borderTop: `1px solid ${colors.bgSurface}`,
    backgroundColor: '#161616',
    padding: '8px 0',
    overflowX: 'auto',
  },
  strip: {
    display: 'flex',
    gap: '4px',
    padding: '0 8px',
    minWidth: 'min-content',
  },
  card: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    minWidth: '96px',
    maxWidth: '120px',
    backgroundColor: colors.bgElevated,
    borderWidth: '2px',
    borderStyle: 'solid',
    borderColor: colors.bgElevated,
    borderRadius: '6px',
    overflow: 'visible',
    transition: 'border-color 0.15s',
  },
  cardSelected: {
    borderColor: '#ff6b35',
    backgroundColor: '#2e1a0f',
  },
  cardHidden: {
    opacity: 0.5,
  },
  thumbBtn: {
    display: 'block',
    width: '100%',
    padding: 0,
    margin: 0,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    position: 'relative',
    outline: 'none',
  },
  thumbnail: {
    width: '100%',
    height: '56px',
    objectFit: 'cover',
    borderRadius: '4px 4px 0 0',
    display: 'block',
  },
  thumbPlaceholder: {
    width: '100%',
    height: '56px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#555',
    backgroundColor: colors.bg,
    borderRadius: '4px 4px 0 0',
  },
  proxyBadge: {
    position: 'absolute',
    top: '4px',
    right: '4px',
    fontSize: '9px',
    color: '#ff6b35',
    backgroundColor: colors.overlay,
    borderRadius: '3px',
    padding: '1px 4px',
  },
  actions: {
    display: 'flex',
    justifyContent: 'center',
    gap: '2px',
    padding: '4px 2px',
  },
  actionBtn: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '24px',
    height: '22px',
    background: 'none',
    border: 'none',
    color: '#777',
    cursor: 'pointer',
    borderRadius: '3px',
    padding: 0,
    outline: 'none',
  },
  empty: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    height: '80px',
    backgroundColor: '#161616',
    borderTop: `1px solid ${colors.bgSurface}`,
  },
  emptyText: {
    color: '#555',
    fontSize: '14px',
  },
};
